name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Node Modules
        uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npm test
        env:
          CI: true

      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.7
        if: matrix.node-version == '18.x' && github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          FOLDER: target/site/serenity
          CLEAN: true
