name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Node Modules
        uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npm test
        env:
          CI: true

      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        if: matrix.node-version == '22.x' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: target/site/serenity
          clean: true
